# .yaml config file
#
# The PID gains and controller settings for ros control must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (my_robot_control.launch).

my_robot:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  # Effort Controllers ---------------------------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_0_joint
    #pid: {p: 100.0, i: 0.1, d: 10.0}
    pid: {p: 0.0, i: 0.0, d: 0.0}
    #pid: {p: 100.0, i: 50.0, d: 200.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_1_joint
    #pid: {p: 100.0, i: 0.1, d: 10.0}
    pid: {p: 0.0, i: 0.0, d: 0.0}
    #pid: {p: 100.0, i: 50.0, d: 200.0}
